title: Your Name
description: A mix of Infrastructure - Platform - Security - AI - Hacking Engineering Stuff
url: "https://habib0x0.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name: Your Name
  email: your.email@example.com

show_excerpts: true
permalink: /:title/

sass:
  sass_dir: _sass
  style: compressed
